### ISSUE TITLE
Date Received saved as UTC time

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1011]
## Steps to reproduce
Create and receive an AR.

## Current behavior
Date Received is saved with time, that is two hours (in my case) behind the local time. Supposedly this is in UTC, while the time of the linux host is set as local time correctly.

## Expected behavior
Date Received is saved in local time.

**Comment by ramonski** [comment]
The issue here is that the calendar widgets store only plain string dates. These are converted w/o timezone information, hence the 2 hour offset for Germany, because we are GMT+2.
But wasn't it `DateSampled`?

<img width="636" alt="analysis requests senaite 2018-08-30 07-15-36" src="https://user-images.githubusercontent.com/713193/44830970-c1802100-ac24-11e8-9bab-61350b52abce.png">

**Comment by grulisco** [comment]
Just created and received a new sample at 9:48 with Date Sampled/Now:

Sample View:
![grafik](https://user-images.githubusercontent.com/25460329/44837673-81c43400-ac3a-11e8-85f4-1454f0721695.png)

See the dates in AR listing:
![grafik](https://user-images.githubusercontent.com/25460329/44838215-e5029600-ac3b-11e8-9e39-6935cd6e2fda.png)

So it seems to me that Date Sampled and its widget is not the problem, but the automatically generated date/time fields without user input.

**Comment by ramonski** [comment]
Indeed, thanks for the detailed issue report @grulisco!

**Comment by grulisco** [comment]
In addition timestamps of remarks (AR, Batches, ...) are wrong too.

**Comment by xispa** [comment]
The same with "Date Sampled"

**Comment by ramonski** [comment]
Still an issue with the date of "Date Sample Received".

- Steps to reproduce:

  - Create a new AR
  - Receive the Sample

- Current Behavior:
   Sample Received Date/Time displayed with 2 hours offset for GMT+2 TZ

- Expected Behavior:
  Sample Received Date/Time displayed w/o offset for GMT+2 TZ

<img width="997" alt="18-00092-r1 liscon lims 2018-09-15 11-45-08" src="https://user-images.githubusercontent.com/713193/45585000-5f3e4600-b8dd-11e8-93cd-2715ae0b7915.png">

**Comment by grulisco** [comment]
Is it possible, that this one is a fundamental plone configuration problem or error?
In ZMI Undo-protocol I see one ar_add with a wrong logged time of 12:52, which was 14:52 in fact:
![grafik](https://user-images.githubusercontent.com/25460329/45586463-0af48f80-b8f8-11e8-9a81-be7c7a2cb3d3.png)

**Comment by ramonski** [comment]
You are right @grulisco, that's a server-side issue.
The timezone was set in the `live.cfg` of an senaite.ansible-playbook built server:

<img width="428" alt="1 root senaitest 192 168 220 15 - byobu ssh 2018-10-05 22-04-27" src="https://user-images.githubusercontent.com/713193/46557571-a753f580-c8ea-11e8-9b9d-d8fc1eca7355.png">

Setting it to `Europe/Berlin` fixed the issue:

<img width="421" alt="1 root senaitest 192 168 220 15 - byobu ssh 2018-10-05 22-10-55" src="https://user-images.githubusercontent.com/713193/46557843-90fa6980-c8eb-11e8-8fff-dc45e6558d04.png">

Also see here: https://docs.plone.org/manage/deploying/zope.html#timezone

**Comment by eyahlin** [comment]
Hello,

I, too, am experiencing this issue.

I have tried @ramonski 's suggestion to change the timezone from Zope, but it didn't work after rebuilding.

Any suggestions? 

EDIT: I found a solution. The timezone format wasn't compatible with zope2.DateTime's available formats. I kept trying different formats until I successfully found a timezone that does work -- "Asia/Singapore". Thank you anyway!

Allan
