### ISSUE TITLE
How to change test request in the to be verify status

### ISSUE THREAD

**Issue by garciagab** [senaite/senaite.core#1204]
## Create an AR with multiple test request, enter results and submit to be verified, then change one of the test request. 

##Unable to move old test request, greyed out. 

## Screenshot (optional)
[Screen Shot.docx](https://github.com/senaite/senaite.impress/files/2762223/Screen.Shot.docx)

Correct: The request is greyed out 
![image](https://user-images.githubusercontent.com/42850389/51361504-7321d080-1aa6-11e9-90bd-4ea9e798d5d7.png)

**Comment by xispa** [comment]
Hi @garciagb , thanks for your contribution!. Please note this issue was not related with `senaite.impress`, rather with `senaite.core`, so I've moved it the issue here, in `senaite.core`'s issue tracker: https://github.com/senaite/senaite.core/issues

As far as I understand (and I might be wrong) you are trying to remove or add tests in an Analysis Request that is in "to be verified" status, but even using a user withh "LabManager" privileges, you cannot unselect/select analyses from "Manage analyses view" and save them. Since the Analysis Request is in "to be verified" state, all the analyses (tests) should at least be in "to be verified" status too, so try first to retract them and see if you are able then to unselect them from "Manage analyses view".

Please confirm if the explanation above is the issue you are referring to. If so, we will appreciate if you can update the issue accordingly (three dots button at top right > Edit) to allow us to apply labels, prioritize and try to reproduce the issue.

NB: Also, better to post screenshots as images (png, jpg) instead of docx
