### ISSUE TITLE
Cannot add test requests for samples/worksheets already verified or published

### ISSUE THREAD

**Issue by garciagab** [senaite/senaite.core#1205]

**Comment by xispa** [comment]
Hi @garciagb , thanks for your contribution!. Please note this issue is not related with `senaite.impress`, rather with `senaite.core`, so I've moved it the issue here, in `senaite.core`'s issue tracker: https://github.com/senaite/senaite.core/issues

By default, system does not allow to add or modify tests from Analysis Requests that are in "verified" or "published" status. These states are basically end points in the Analysis Request workflow. You have different options here:

- **Invalidate the Analysis Request**: when an Analysis Request is invalidated, the system automatically generates a "copy" and transitions this copy to "received" status. This "copy"n (retest) has same analyses and results previously set in the invalidated Analysis Request. Since the retest is in "received" status, the system allows you to manage its analyses (add/remove tests). If the Analysis Request is invalidated after it was "published", the system will automatically send an email notification to the client contact, stating that the Analysis Request has been invalidated and therefore, the results report is no longer valid. 

- **Secondary Analysis Request**:  You have the option to keep the previous Analysis Request valid, but generate a Secondary Analysis Request with additional tests. Go to Analysis Request Add form, choose the same Sample as the previous Analysis Request in field "Sample".

- **Copy to new**: There is the option to create a new Analysis Request without invalidating the previous one, but keeping exactly the same tests and sample information as the primary. Go in the Analysis Requests listing, choose the Analysis Request you want to copy and press the "Copy to new" button. The AR Add form will be displayed with same values as the primary one.

- **Customize Analysis Request workflow**. This requires coding skills.

NB: Please try to stick to the sections the issue template provides when creating issues, it will make reviewer's live easier!

**Comment by garciagab** [comment]
Invalidate the Analysis Request:  Error 

![image](https://user-images.githubusercontent.com/42850389/51360781-7c5d6e00-1aa3-11e9-9048-48a22ddd1a8b.png)

![image](https://user-images.githubusercontent.com/42850389/51360676-05c07080-1aa3-11e9-8d84-7b2021b41362.png)

Secondary Analysis Request:  Error 

![image](https://user-images.githubusercontent.com/42850389/51360812-99923c80-1aa3-11e9-9e94-443a6b5e9599.png)

![image](https://user-images.githubusercontent.com/42850389/51360819-a2830e00-1aa3-11e9-9491-c5432dc5ae66.png)

Copy to new: 
 Created a new AR number with no link to the old AR number

**Comment by xispa** [comment]
The Traceback you get when creating a retest and the error when you try to create a secondary AR are because of the same reason. The ID generated for the new AR (secondary or retest) crashes with an already existing ID. I think the reason is because there is no separator between the sample ID and the "request" part: `000639R0` instead of `000639-R0`.

Basically, the system tries to keep the same ID as the invalidated or primary Analysis Request, but increase the digit of the last part (the suffix) in one unit. Since there is no "separation" character explicitly set, the system is unable to recognize the last part and tries with the same ID. But the ID already exists, so the system cannot create this new entity and the error is rised.

Although we could add an hyphen in the ID between the sample id and the request number, not sure if this is a good solution given the fact you have Analysis Requests already created. Please confirm. Another solution that wouldn't require any change in your current IDs configuration, would be to make ID Server to support fixed-length parts in IDs too, at least for these two specific cases (secondary + retest): the system would look for fixed-length parts instead of specific char when splitting the ID.

I've assigned the issue to myself.

**Comment by garciagab** [comment]
Can we change the R0 to R1 so we have  
000639R0 
as the original 
and 000639R1 
for these two specific cases (secondary + retest)

**Comment by xispa** [comment]
Thanks @garciagab , opened an issue for this specific "Advanced..." issue here:
https://github.com/senaite/senaite.core/issues/1219

Regarding the AR numbering: your "primary" AR already ends with "R0". Indeed, the rest of ARs generated from the primary as the source (e.g. retests or secondary) should follow the criteria "R1", "R2", etc.

**Comment by garciagab** [comment]
R1 , R2 is ok for me.

**Comment by xispa** [comment]
Related: https://github.com/senaite/senaite.core/pull/1229

**Comment by grulisco** [comment]
@xispa two questions to your initial comment:
* **Secondary Analysis Request**:  You have the option to keep the previous Analysis Request valid, but generate a Secondary Analysis Request with additional tests. Go to Analysis Request Add form, choose the same Sample as the previous Analysis Request in field "Sample".

In current master (pre1.3) the field "Sample" is lost, so this option is not available. Is it planned to reintroduce this field?
 
* **Copy to new**: There is the option to create a new Analysis Request without invalidating the previous one, but keeping exactly the same tests and sample information as the primary. Go in the Analysis Requests listing, choose the Analysis Request you want to copy and press the "Copy to new" button. The AR Add form will be displayed with same values as the primary one.

This kind of copy will not keep old sample received date, or does it?

**Comment by xispa** [comment]
Hi @grulisco 

> In current master (pre1.3) the field "Sample" is lost, so this option is not available. Is it planned to reintroduce this field?
Yes, and atm we believe we have the new code base stable enough to add this feature without undesired effects. In fact, secondary sample (along with some sporadic bugs that are reported here for 1.3) is the last remaining thing before making 1.3 public. Our idea is to have it ready for testing within the following days.

> This kind of copy will not keep old sample received date, or does it?
No, this kind of copy does not copy values of fields somehow related with transitions. So, no it does not keep old sample received date.

**Comment by grulisco** [comment]
Hi @xispa:
I wouldl gladly test secondary sample machinery as soon as it is available.
Normal copy sample: At least received date is editable after copying...

**Comment by xispa** [comment]
@grulisco https://github.com/senaite/senaite.core/pull/1284 :1st_place_medal:

**Comment by xispa** [comment]
Fixed in 1.3 See https://github.com/senaite/senaite.core/pull/1284 and https://github.com/senaite/senaite.core/issues/1219

**Comment by grulisco** [comment]
:+1:
