### ISSUE TITLE
Analysis request causes error

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#1210]
## Steps to reproduce
Choose "Analysis request" 
Senaite.core version: 1.29

![image](https://user-images.githubusercontent.com/38714119/51661382-00868880-1fb1-11e9-924e-275f54cf1523.png)

## Current behavior

The following error occurs:

![image](https://user-images.githubusercontent.com/38714119/51661327-d59c3480-1fb0-11e9-9828-7f84429f99f5.png)

## Expected behavior
No error should occur
## Screenshot (optional)
see above

**Comment by Migulo** [comment]
Thanks for the fast reply --> Problem solved due to your advice.

Thanks again.

PS: From my point of view, it would be helpful to add the proper upgrade procedure to you upcoming documentation.

**Comment by ramonski** [comment]
Yes indeed, documentation is something we are lacking at the moment in the Senaite Project.

Probably after release 1.3 we will focus more on that topic, because we changed a lot from the point of the logic as well as the user interface. Basically 1.3 will be like a new system...

Please don't forget to close the issue if it is solved for you.

**Comment by ramonski** [comment]
Closing this one, please re-open if you encounter further problems regarding this issue @Migulo
