### ISSUE TITLE
Keep more sample metadata editable

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1227]
## Steps to reproduce
- create sample with any analysis
- enter many sample metadata (e.g. csid, client reference, sampling date, sample deviation, container, environmental conditions, etc.)
- receive sample

## Current behavior
The metadata fields are handled differently in editing through the normal workflow.
Sometimes they need to be changed afterwards (e.g. due to own mistakes or updated client information) while some are editable and some are not (see screenshot).
Especially sampling date (which **we** get from the client request) cannot be corrected in any way after registration.

## Expected behavior
The metadata of samples (mainly based on client's information) should all be editable at least up to verified state.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/52300514-4e739700-2988-11e9-9142-08f96cbd156c.png)

**Comment by xispa** [comment]
Most of these fields (if not all) were editable in "sample due" state. One expects the user to check the sample conditions (the container is not broken, the sample is suitable for the tests requested, etc.) and the information provided (the metadata) at reception, while the sample is still in "sample due" state. Once all is in place (the metadata is ok too), then the user might "receive" the sample. Otherwise, the "receive" transition is kind-of "fluffy": too easy to receive without paying required attention. Hence, we made fields edition more restrictive in "received" status.

Making these fields editable at this status can be done by adding the required write permissions for each field in `ar_workflow`. This requires programming skill though.

Nevertheless, maybe we've been too restrictive and wouldn't be a problem to make some of them editable while keeping the "importance" of the "receive" transition. Which are the fields you think should be editable at "received" status?

**Comment by ramonski** [comment]
I rather think of the use-case when the lab receives the sample physically and scans the barcode at reception. Then the system should receive the sample automatically and the lab analyst (maybe a couple of hours later) should check if the metadata is as stated initially and should be able in that state to change
I think reception should not be coupled with checking the sample for correctness. Therefore,  I would simply allow to edit the fields in the received state.

**Comment by xispa** [comment]
Good point @ramonski . For this use-case there is the option to add an additional "on_review" status between "sample_due" and "sample_received", but understand this would increase the complexity unnecessarily. Making editable some fields in "received" status would be easier and would fit with most labs. The following fields can be made editable in "received" status:

- Environmental conditions
- Batch
- Batch Sub-group
- Container
- Preservation
- Sample Point
- Sampling Deviation
- Sample condition
- Composite

"Sampled Date" can be editable, but requires a validator to ensure the date introduced is not after the date the sample was received.

The following fields **must remain readonly**: "Sample Type", "Analysis Profiles" and "Sample Template", cause they are strongly bound and editing one of them might cause inconsistencies. If the value for any of these fields was found to be wrong, then the only choice is to reject the sample.

**Comment by grulisco** [comment]
Valid arguments @xispa and @ramonski!

> The following fields **must remain readonly**: "Sample Type", "Analysis Profiles" and "Sample Template", cause they are strongly bound and editing one of them might cause inconsistencies. If the value for any of these fields was found to be wrong, then the only choice is to reject the sample.

That would be OK.

I agree that with receiving samples their metadata should be checked thoroughly. But shit happens and accidental slips and mistakes too. So I tend to keep those fields editable as long as possible at least until verification for managers or verifiers.
