### ISSUE TITLE
Leap sample ID sequence after secondary sample

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1327]
## Steps to reproduce
- Create secondary sample of any existing sample
- Create another sample of the same type (e.g. copy above) later

## Current behavior
Secondary sample gets id with old sample id with suffix -S01, OK.
The next new sample does not get the next available sample id.
This will produce gaps in ID-Sequence.

## Expected behavior
The next new sample gets the next available sample id.
(In the example H2O-0051 should actually be -0049 or 0050).

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/55960895-0285ec80-5c6e-11e9-8cd0-1e6ac8c61cbf.png)

How is the ID-Server involved in those cases?

**Comment by xispa** [comment]
Devs note: these ID gaps do not happen in secondary ARs only, but with partitions too. The reason is that `_renameAfterCreation` is called just after the object is created. In some particular cases, especially for AnalysisRequest objects, additional values (e.g. `PrimaryAnalysisRequest` to make a Sample secondary, or `ParentAnalysisRequest` to make a Sample a partition) are set after this initialization and the idserver is called again afterwards:

- An "initial" ID is created here: 
https://github.com/senaite/senaite.core/blob/77177d3c4e9c3ba7e1fa1b8869a24a5b427dcd92/bika/lims/utils/analysisrequest.py#L81-L82

- Since this is a secondary, the previous ID is replaced by a new one later here: 
https://github.com/senaite/senaite.core/blob/77177d3c4e9c3ba7e1fa1b8869a24a5b427dcd92/bika/lims/utils/analysisrequest.py#L90-L96

Hence, a new ID is created, but the old one created during initialization is kept in the idserver annotations dict. The result is that idserver machinery will assume the last id created for this type of object was the one assigned during initialization and therefore, a gap in the IDs is generated

**Comment by ramonski** [comment]
@xispa I cannot confirm that this happens for partitions as well, because partitions are created explicitly by the `create_partition` function: https://github.com/senaite/senaite.core/blob/master/bika/lims/utils/analysisrequest.py#L371

Please confirm that you just expected this behaviour rather than that it actually encountered for partitions.
