### ISSUE TITLE
Remove the "Switch to frontpage" button

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.core#1370]
## Steps to reproduce

When a user clicks on the button, the dashboard goes away for all users.

From my perspective this functionality does not provide any valuable improvement and may become confusing for users that cannot go back to the dashboard view.

In case a laboratory wants to display a custom page, this can be added in its own addon.

**Comment by ramonski** [comment]
Hi @Espurna, this button is actually only a simple redirect (e.g. https://senaite.ridingbytes.com/?redirect_to=frontpage) and shouldn't have any effects on other users. How did you encounter that for other users?

The place where the dashboard can be set permanently to a static page is via the setup:
<img width="1296" alt="Setup — SENAITE 2019-05-16 17-37-08" src="https://user-images.githubusercontent.com/713193/57867351-45088f00-7801-11e9-93f1-5e2987e371e2.png">

The reason why this exists is because the dashboard takes a long time to load for big databases and slows down the whole site when people initially log-in to the system at same times.

Therefore, I would rather put the dashboard in an own add-on and make the standard page always a static and editable Plone page.

**Comment by Espurna** [comment]
mmm okay, I will close that one then. I had the feeling that from time to time I was redirected to the front-page but I have never done this with my user...

**Comment by xispa** [comment]
> Therefore, I would rather put the dashboard in an own add-on and make the standard page always a static and editable Plone page.

:+1: One of the things in my TODO list, precisely
