### ISSUE TITLE
Cannot import Winescan FT120 csv

### ISSUE THREAD

**Issue by siyamalan** [senaite/senaite.core#1375]
https://github.com/senaite/senaite.core/blob/d0ff452b52eeadabdfaa6b849a20817694c28418/bika/lims/exportimport/instruments/foss/winescan/ft120.py#L143

Hi,

I am getting below error message while trying to import CSV file from ft120
`Traceback (most recent call last): File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 79, in Import importer.process() File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/resultsimport.py", line 415, in process self._parser.parse() File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/resultsimport.py", line 246, in parse jump = self._parseline(line) File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 113, in _parseline return WinescanCSVParser._parseline(self, line) File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/foss/winescan/__init__.py", line 104, in _parseline self._addRawResult(resid, outvals, True) File "/home/vlabbka/Plone/zeocluster/src/senaite.core/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 154, in _addRawResult values[keyword]['DateTime'] = dateTime UnboundLocalError: local variable 'dateTime' referenced before assignment`

csv file attached below
[Test 02.txt](https://github.com/senaite/senaite.core/files/3195006/Test.02.txt)

I tried again by reformatting this csv file to Winescan Auto format and changing the import interface to winescanAuto and import worked fine
<img width="1091" alt="ft120" src="https://user-images.githubusercontent.com/20146320/57981497-4d282f00-7a8c-11e9-85c9-446830c48057.PNG">

Can this be fixed

**Comment by mikejmets** [comment]
Hi @siyamalan. I don't know this instrument code but [this line](https://github.com/senaite/senaite.core/blob/d0ff452b52eeadabdfaa6b849a20817694c28418/bika/lims/exportimport/instruments/foss/winescan/ft120.py#L141) in the code gives the example "2/11/2005 13:33 PM" for the date format required in your results file.  The code should be more robust because [this line](https://github.com/senaite/senaite.core/blob/d0ff452b52eeadabdfaa6b849a20817694c28418/bika/lims/exportimport/instruments/foss/winescan/ft120.py#L146 ) swallows the error that is found wrt the date time in your input file. You maybe better off remove the try/except and let it fail.

**Comment by siyamalan** [comment]
> Hi @siyamalan. I don't know this instrument code but [this line](https://github.com/senaite/senaite.core/blob/d0ff452b52eeadabdfaa6b849a20817694c28418/bika/lims/exportimport/instruments/foss/winescan/ft120.py#L141) in the code gives the example "2/11/2005 13:33 PM" for the date format required in your results file. The code should be more robust because [this line](https://github.com/senaite/senaite.core/blob/d0ff452b52eeadabdfaa6b849a20817694c28418/bika/lims/exportimport/instruments/foss/winescan/ft120.py#L146) swallows the error that is found wrt the date time in your input file. You maybe better off remove the try/except and let it fail.

@mikejmets it was an easy fix. 
Removed %S and import is now working properly.  Date Time in winescan csv file doesn't contain seconds information
![image](https://user-images.githubusercontent.com/20146320/58014532-2f6ece80-7b4d-11e9-814b-7e1b99ee4d15.png)

**Comment by mikejmets** [comment]
Removing the seconds solves your problem with your site but it could break someone else's site. You raise an issue that needs top be address but the community at large, that is, how can instruments interfaces be customised at a site level. I have raise the issue here https://github.com/senaite/senaite.core/issues/1366

**Comment by siyamalan** [comment]
@mikejmets this issue was there with bika as well. Kept unaddressed this long. Ft120 csv files never had seconds information. More ft120 sample csv files sitting at bika  https://github.com/bikalims/bika.lims/issues/2037
Cheers

**Comment by xispa** [comment]
Just checked the format for Ft120 file in our samples (https://github.com/senaite/senaite.core/tree/master/bika/lims/exportimport/instruments/foss/winescan/samples) and seems @siyamalan is right:

https://raw.githubusercontent.com/senaite/senaite.core/master/bika/lims/exportimport/instruments/foss/winescan/samples/ft120_full.csv
