### ISSUE TITLE
Creation of secondary samples not possible

### ISSUE THREAD

**Issue by RaabJoh** [senaite/senaite.core#1408]
## Description

Secondary Sample can not be generated from every primary sample, but only from a few. "Tertiary" sample could be generated from several secondary samples.

## Observed behaviour

Several primary samples can not be chosen as source for secondary samples.

## Expected behaviour

Each primary sample can be chosen as source for the secondary sample.

## Versions

I'm using senaite 1.3.0 running on Ubuntu 16.04 with
Plone 4.3.18 (4320)
CMF 2.2.10
Zope 2.13.28
Python 2.7.13 (default, Feb 28 2018, 07:03:23) [GCC 5.4.0 20160609]
PIL 4.1.0 (Pillow)

## Screenshot

![SampleList](https://user-images.githubusercontent.com/52410468/60663066-76472800-9e5e-11e9-9aed-f1b81ec9a24e.PNG)
![SecondaryCreation](https://user-images.githubusercontent.com/52410468/60663067-76472800-9e5e-11e9-9bae-e72d084cf692.PNG)

Unfortunately I'm not coding myself but only trying to establish the senaite.lims system in our Lab and am therefore quite unexperienced and not helping much in finding the error. Sorry for that.

**Comment by ramonski** [comment]
Hi @RaabJoh, thanks for reporting.

It seems like some of the Samples caused an internal error due to an invalid ID template (see the 26 alphanumeric IDs in the first screenshot).

These Samples were not correctly indexed in the database and therefore not displayed in the list.

Please revert your ID template for Samples and confirm if the new created samples are displayed in the widget afterwards correctly. Also consider to update your instance to the latest versions of Senaite (currently `senaite.core` 1.3.1).

**Comment by RaabJoh** [comment]
Hello @ramonski, thanks for the fast answer.

That actually worked for newer samples but e.g. 19-SCR-0006 generated an actual sample name and can't be chosen for creating a secondary sample. But there might be some problem with my ID generation for samples. For now I will go back to the standard ID generation which works fine, until I figured out a working way to individualize the sample IDs.

I already requested my instance to be updated by the IT department. 

Thank your for your help and patience.
