### ISSUE TITLE
Confusing batch reference fields 

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#1457]
## Description
Changing or setting the batch within the sample view is quite confusing, because it's at least difficult to find a corresponding batch.

## Reproduction guide
- Create a sample
- Click into the empty batch reference field
- Popup with a set of existing batches appears

## Observed behaviour
- The popup list is limited to 30 items, even if there are more batches
- this list is sorted arbitrarily
- it shows the columns BID, CBID and Client
- None of those fields can be filtered, neither by full batch id
- CBID is always empty, even if there is content
- it can be filtered by batch title only in blind flight

## Expected behaviour
- popup shows all open batches at first
- reasonable sorting
- batch title is displayed too
- display all content
- filter by keywords over all columns

## Versions
- OS: Linux
- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Screenshot
![image](https://user-images.githubusercontent.com/25460329/66782026-163c3500-eed5-11e9-868b-e4ef2f0b2382.png)

**Comment by xispa** [comment]
The following issues have been addressed in https://github.com/senaite/senaite.core/pull/1450 :

- *The popup list is limited to 30 items, even if there are more batches*
  Limited to 50 items now
- *this list is sorted arbitrarily*
  the items are sorted by creation date descending (more recent first)
- *None of those fields can be filtered, neither by full batch id*
  search term is used now to search against all Batch' fields
- *CBID is always empty, even if there is content*
  CBID is now displayed
- *it can be filtered by batch title only in blind flight*
  search term is used now to search against all Batch' fields

And regarding the "expected behaviour":

- *popup shows all open batches at first*
  by default, only batches in "open" status are displayed
- *batch title is displayed too*
  added "Title" column in the reference widget selection list
- *filter by keywords over all columns*
  search term is used now to search against all Batch' fields
