### ISSUE TITLE
Add New client button missing from the Request new analyses page

### ISSUE THREAD

**Issue by ronna** [senaite/senaite.core#1608]
## Description

The add new client button is missing from the Request new analyses page

## Reproduction guide

Log in to the LIMS systems, click Samples menu, Request new analyses, 

## Observed behaviour

There is no Add New Client button

## Expected behaviour

Add new client button should appear next to the client selection box 
## Versions

- OS: Linux

- senaite.core: `.1.
![add_client](https://user-images.githubusercontent.com/1917293/88152678-a9dd2780-cc04-11ea-91b3-6dddd2ca93c5.png)
3.3.1`
- senaite.impress: `1.2.3`
- senaite.core.listing: `1.4.0`
- senaite.core.supermodel: `not installed`
- senaite.lims '1.3.3.2'

## Screenshot

Expected Behaviour (screenshot from version SENAITE Core 1.3.3 , SENAITE LIMS 1.3.2.1 )

![add_client](https://user-images.githubusercontent.com/1917293/88152743-c24d4200-cc04-11ea-878b-cd2a11470926.png)

Missing Button

![missing_add](https://user-images.githubusercontent.com/1917293/88152892-f7599480-cc04-11ea-92cf-75661c9746c5.png)

**Comment by Espurna** [comment]
@ronna Thanks for pointing it out, but this is not an issue but a design decision from October 2019. You can find the Pull request and the reason for this decision here: https://github.com/senaite/senaite.core/pull/1462

**Comment by xispa** [comment]
@ronna the "Add/Edit" button overlay was removed in https://github.com/senaite/senaite.core/pull/1541 as part of a code cleanup in order to improve the quality of the code to make it more reliable and sustainable. Besides the inherent complexity of the Add Sample form and the old-school js functionality behind, that code was no longer maintained and it was too difficult to maintain.
