### ISSUE TITLE
2-Dimensional CSV Data Import ignores "-"

### ISSUE THREAD

**Issue by ghost** [senaite/senaite.core#1615]
## Description

Importing data using the 2-Dimensional CSV interface seems to split string if the analysis keyword is using a "-" as part of the name

## Reproduction guide

Using the following CSV import ignores the "-" while importing:

ID,HM-010_Ca,HM-010_Mg,end
WM-0007,211,322,
end

## Observed behaviour

After import the protocol says that for the named analysis keyword "HM010_Ca" and "HM010_Mg" no data was found. This clearly shows that the "-" is deleted.

## Screenshot
<img width="672" alt="Bildschirmfoto 2020-08-27 um 08 50 24" src="https://user-images.githubusercontent.com/70312626/91405984-5e8ce900-e842-11ea-89be-3540064dbb60.png">

**Comment by rockfruit** [comment]
Last night I read up about this and I understand that this is the expected behaviour, since the Keyword needs to have the syntax of a valid identifier.  The solution would be to create the service with the keyword "HM010_Mg", the translation won't change shape.

I'm making a little patch to include documentation of this sort (and specifically for each interface) in the UI.
