### ISSUE TITLE
Reports destiny: to be or not to be 

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2351]
hello :) @ramonski 

I've noticed that with the latest update the Reports section was wiped out (#2334 )

Is reports functionality supposed to move somewhere else or it is going to be fully eliminated? 

regards,
--leo

**Comment by ramonski** [comment]
Hi Leonid,

Yes, we removed the reports entirely from the core since we want to focus there on pure sample management and don't want to mix it with controlling/business intelligence capabilities.

Furthermore, large generated reports via PDF resulted in such a high load on the server, that no one else was able to work – which is a pain.

Additionally, every piece of legacy code/functionality we do not have to port to Dexterity or make it Python 3 compatible brings us closer to our goal to make Senaite Python 3 (or maybe then even Python 4) compatible;)

Maybe you can use senaite.databox for the data you are interested in and generate an Excel out of it for further processing?

Anyhow, thanks for understanding that we need to focus on the core functionalities to bring Senaite forward.

Best regards
Ramon

**Comment by toropok** [comment]
Thank you @ramonski 

That's really makes sense and picture becomes clear. You're wisemen indeed ;) 

--leo
