### ISSUE TITLE
published_result action error appears 

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2353]
## Description

published_results action called from a sample view falls to error screen. No logs error appear. Where to check that?

## Reproduction guide

click published results 
<img width="902" alt="Screenshot 2023-07-27 at 11 35 15" src="https://github.com/senaite/senaite.core/assets/14867014/ec3fe16a-588d-4acd-a06c-d15b3b67cae8">

## Observed behaviour

delivers error screen 

<img width="1063" alt="Screenshot 2023-07-27 at 11 31 57" src="https://github.com/senaite/senaite.core/assets/14867014/371c753f-c340-4075-8902-847aae2e90b6">

## Versions

- OS: Linux

- senaite.core: 2.5

**Comment by ramonski** [comment]
Hi @toropok,
the error does not apply in a fresh installation of SENAITE with the demo data provisioned:

<img width="1325" alt="H2O-0001 — SENAITE LIMS 2023-07-27 12 PM-15-35" src="https://github.com/senaite/senaite.core/assets/713193/ccf346da-13fa-4e8b-b6f2-4090973bf2a3">

Have you maybe customized that view?

Hint: Errors like this appear mostly when an error happens in the views' `__init__` method. Note that the Zope Component Architecture (ZCA) might not be fully initialized at that point or maybe permission checks fail because your user is considered as `Anonymous` user.

**Comment by toropok** [comment]
@ramonski 

yes, you're right my bad :) thank you for the hint!
