### ISSUE TITLE
Sample auto receive feature sets "Received" despite who creates the sample

### ISSUE THREAD

**Issue by toropok** [senaite/senaite.core#2418]
## Description

When we have "Auto-receive samples" mode enabled -  it says that newly created sample sets as "received" automatically in case it has been created by lab staff or "sample due" if not.

## Observed behaviour

after some recent updates this mechanism works a bit wrong. Any new sample is "Received", no matter who is creator.

## Expected behaviour

Client samples is "sample due" by default if this option is enabled.

Seems that condition evaluation need to be added on that line:

[/src/bika/lims/utils/analysisrequest.py:144](https://github.com/senaite/senaite.core/blob/4004f1ab425ab6bbad3887eb36da8a05ecb02d67/src/bika/lims/utils/analysisrequest.py#L144)

```
    if not IReceived.providedBy(ar):
        setup = api.get_setup()
        # Sampling is required
        if ar.getSamplingRequired():
            changeWorkflowState(ar, SAMPLE_WORKFLOW, "to_be_sampled",
                                action="to_be_sampled")
        elif setup.getAutoreceiveSamples() and not api.get_current_client():
            receive_sample(ar)
        else:
            changeWorkflowState(ar, SAMPLE_WORKFLOW, "sample_due",
                                action="no_sampling_workflow")
```

@ramonski is that correct logic? if so we will add it as PR

**Comment by ramonski** [comment]
Hi @toropok,
thanks for reporting your findings in this issue!

The code above is not the right solution to this problem, because also a client contact might have the permission granted to receive a sample.

The right solution is rather to pass in `check_permission=True` to the `receive_sample` function in line 145.

Can you check if this solves your issue?

**Comment by ramonski** [comment]
Hmm, it seems like the permission check does not work for the temporary sample at this stage.
Maybe it is sufficient for this functionality to check if the current user has the `LabManager` role instead of checking the permission of on the object itself.

**Comment by ramonski** [comment]
For the records:

With https://github.com/senaite/senaite.core/pull/2359 we increased the performance for the sample create process by changing the initial workflow state of samples from `sample_registered` to `sample_due` or `sample_received` directly and bypass the transition.

Due to this change, we also move from `sample_registered` -> `sample_received` directly.

However, at the state `sample_registered`, we do not allow any permissions.
Therefore, a permission check for `senaite.core: Transition: Receive Sample` will always return false, no matter which role the current user has.

Also see the comment in the code at https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/utils/analysisrequest.py#L179-L187:

```python
def receive_sample(sample, check_permission=False, date_received=None):
    """Receive the sample without transition
    """
    # NOTE: In `sample_registered` state we do not grant any roles the
    #       permission to receive a sample! Not sure if this can be ignored
    #       when the LIMS is configured to auto-receive samples?
    if check_permission and not can_receive(sample):
        return False
    ...
```

This leaves us with the following options:

1. Grant the permission `senaite.core: Transition: Receive Sample` at the state `sample_registererd` to the default roles.
2. Check just the roles of the current user and allow only e.g. `LabManager` and `LabClerk` to receive the sample.
3. Check the default roles for the permission `senaite.core: Transition: Receive Sample` and check if the current user has one of these roles granted.

**Comment by xispa** [comment]
I vote fot the first option, grant the `senaite.core: Transition: Receive` Sample at the state `sample_registered` to the default roles. At least it feels less an exception to the norm.

**Comment by xispa** [comment]
Another option would be to "always" try the transition, without the need of checking the value for the setting at setup. And let the mutator of the setup settint to grant/revoke the permission for default roles in sample_workflow and `registered` status.

**Comment by ramonski** [comment]
It should be fixed with https://github.com/senaite/senaite.core/pull/2419
Please check @toropok and give feedback if this works for your use case as well.

**Comment by toropok** [comment]
> It should be fixed with #2419 Please check @toropok and give feedback if this works for your use case as well.

@ramonski im sorry for long waiting. Please, check our microfix below (line 144), this makes it work amazing :) just as before for our use-case.

With the code you proposed, when client create sample it appears to be in "Registered" state. However if I understand this `if-elif-else` block properly  the result state should be "sample due".

```python
    if not IReceived.providedBy(ar):
        setup = api.get_setup()
        # Sampling is required
        if ar.getSamplingRequired():
            changeWorkflowState(ar, SAMPLE_WORKFLOW, "to_be_sampled",
                                action="to_be_sampled")
        elif setup.getAutoreceiveSamples() and can_receive(ar):
            receive_sample(ar)
        else:
            changeWorkflowState(ar, SAMPLE_WORKFLOW, "sample_due",
                                action="no_sampling_workflow")
```

thanks a lot for your time and attention!

**Comment by xispa** [comment]
You are right @toropok . If the client does not have the permission `senaite.core: Transition: Receive` granted, the sample should transition to `sample_due`. With the `if-else` above, the sample won't transition otherwise, but remain in `registered` status. Will open another PR

**Comment by toropok** [comment]
thanks guys!
