### ISSUE TITLE
Remarks field on Report with TinyMCE

### ISSUE THREAD

**Issue by ngslabex** [senaite/senaite.core#2497]
## Description

The results of cytogenetic test analyzes are based on interpretation and often chromosome images need to be added. 

## Observed behaviour

Cytogenetic analysis results are independent of any threshold and warning values and are based on interpretation.

## Expected behaviour

I think this situation can be met by giving the Remark field a rich text feature.

## Versions

- OS: Linux

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

## Screenshot
![image](https://github.com/senaite/senaite.core/assets/44006041/b16ce83f-c5f5-4c50-9511-5af619401659)

**Sample FISH Report:**
![image](https://github.com/senaite/senaite.core/assets/44006041/55b03da5-5047-4f88-b69e-6fff7af5ad75)

**Comment by grulisco** [comment]
Hi @ngslabex
generally I would like to extend analysis remarks to rich htext or html content for myself, but...

As I understand plone/senaite (I'm not a delevoper), it's not recommended to put images into text fields in a large number because of database performance issues.

And even now, you can upload images to a sample, that should be finally displayed in the report between the results and interpretation block.

Code see:
https://github.com/senaite/senaite.impress/tree/2.x/src/senaite/impress/analysisrequest/templates

In our lab we have the same issue with sem microscopy and enrich our reports with images this way.

I can still imagine an more advanced way of displaying images depending on the upload mode (to sample or to specific analysis), but this would need more customization of the report code.

**Comment by ngslabex** [comment]
Hi @grulisco ,

Thank you very much for your insightful response and the helpful information.

I have resolved the issue by attaching images to the sample, and it works perfectly in the reports. I apologize for the delayed response as I took some time to test it thoroughly.

Please find attached a screenshot of the result for your reference.

Again, thank you for your support and assistance.

Best regards,
![image](https://github.com/senaite/senaite.core/assets/44006041/9a6a9bea-9d5f-4f34-938c-97ea607c8314)

![image](https://github.com/senaite/senaite.core/assets/44006041/106e5bd2-726c-4f51-a6b5-84dc4d76076a)

**Comment by ngslabex** [comment]
I have solve with attach as image file.
