### ISSUE TITLE
Add client types and client licenses

### ISSUE THREAD

**Issue by mikejmets** [senaite/senaite.core#540]
## Expected behavior
The main purpose is to allow relevant licensing information to be rendered on COAs. 

Create new content type `ClientLicenseType` and a new datagridfield `ClientLicense` for `Client`.   `ClientLicense` will have four columns:
* Client License Type
* License ID
* Registration Number
* Issuing Authority

**Comment by ramonski** [comment]
Hi Mike, I have a question abut this change.

As far as I can remember one of these additional contents was "Client Type", kind of a folder in the Setup where different "Client Types" could be added, and then referenced in a Client?

Did you overwrite therefore an existing field in the Client?

I think @grulisco had some limitations with that approach, that he was forced to add these types instead of having a free-text field.

Maybe we can address this correctly during the porting or even put it in an add-on?

**Comment by mikejmets** [comment]
This is the same code that is in 3.4 except with a name change from ClientType to ClientLicenseType to avoid any confusion that is just about licensing. Does anyone else see a use for this in other sectors? Health?

**Comment by grulisco** [comment]
@ramonski my problem was not with client types but with client department types that were linked to department field of contacts. So I'm off-topic here...

**Comment by ramonski** [comment]
Closing, because I think this belongs more to an add-on than in the core
