### ISSUE TITLE
Fix client batch list filters

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#574]
## Steps to reproduce
Go to clients batch list (e.g. https://senaite.ridingbytes.com/clients/client-1/batches) that contains several batches with different states.

## Current behavior
All batches are displayed.

## Expected behavior
Only the matching batches (open/closed/cancelled) are displayed.

## Screenshot (optional)
![grafik](https://user-images.githubusercontent.com/25460329/34958766-8ffde750-fa33-11e7-897b-4de125e60b0f.png)

**Comment by rockfruit** [comment]
It's happening because the batch listing view does not retrieve a list of batches from the catalog.  Instead, it retrieves all the Client's ARs from the catalog, then manually collects the batches on which they appear, and shows those: https://github.com/senaite/senaite.core/blob/c70d2b4538b92c29abafdd17bf9f8530d7e190a7/bika/lims/browser/client/views/batches.py#L25

I think the code above is slow and dumb enough to remove completely, and rather let the "Client Batches" view show only the batches which have a client specified in the Client field of the batch itself.

Agree?

**Comment by xispa** [comment]
Totally agree @rockfruit . I think `contentsMethod` function can be removed at all and just use `self.contentFilter` in `__init__`. E.g: https://github.com/senaite/senaite.core/blob/c70d2b4538b92c29abafdd17bf9f8530d7e190a7/bika/lims/browser/client/views/samplingrounds.py#L20-L26
