### ISSUE TITLE
AR Create. Default Specifications not selected

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#601]
## Steps to reproduce

enable Specifications and select a default lab set of specifications per Sample Type to use, say the lab's

![image](https://user-images.githubusercontent.com/1196034/35335562-9bd2d42c-011e-11e8-8208-f2504794c2f3.png)

Proceed to create new ARs with the Specifications field showing.  and select a Sample Type for which Specifications exist

When the Sample Type is selected, the user expects the default specs for that Sample type to be applied and the Specifications field on the AR Create form completed

## Current behavior

The Specs field stays empty and it has to be completed manually. Note that the default container completed correctly

![image](https://user-images.githubusercontent.com/1196034/35335845-4ddc3ec4-011f-11e8-8616-e5bcdef79ddb.png)

The lookup works correctly, listing only the spec(s) available for the Sample Type

![image](https://user-images.githubusercontent.com/1196034/35336041-d04e7804-011f-11e8-9e40-1adfa7f16409.png)

## Expected behavior

for the Default spec to be applied on the AR form automatically

![image](https://user-images.githubusercontent.com/1196034/35336143-22c56a3e-0120-11e8-92b7-cfbc8f887446.png)

**Comment by lemoene** [comment]
Probably better documented in duplcate https://github.com/senaite/senaite.core/issues/643

**Comment by ramonski** [comment]
These values can be selected in the global setup and per client:

- Analysis Request Specifications
- Sample Type Specifications (Lab)
- Sample Type Specifications (Client)

Depending on the combinations, the Specs for each column of the AR Add form needs to be queried by the catalog and filtered. If multiple Specs were found, e.g. for the Sample Type "Wheat", one of these need to be picked and inserted, if no previous value was set in the Specs field (Probably the one with the most current date).

Special handling needs to be done if AR Add was opened on Batches or on AR listing, since there is no client or the client can be changed by the user.

All of this computation, which significantly slows down the whole AR Add process depending on the rendered columns, is done to fill a field with a value that is probably not the one that the user wants to save a single click?

IMO this functionality should go away completely, because I doubt someone is using it or knows which Spec will be finally diced in the end.

**Comment by lemoene** [comment]
The System needs a specification to compare captured routine results with - essential in any LIMS. In production labs several sets of specs will be available. Which in the very end is used to highlight out of range results on the COA to the client.

Analysis specification is a well matured feature in place since Bika 1, users could even switch between lab and client specs on AR and WS views and the alerts would adjust accordingly.

Having the default spec working, saves the (often specification-illiterate) clerk needing to think which one to choose, making mistakes that have to be corrected, and a click, scroll and click per AR created.

_Analysis Request Specifications_ have been done away with already and should not be a factor

Except for multi-client Batches, ARs are always created in Client Context. Multi-Client batches is more prevalent in research labs, and because of all the client referenced ancillary data in some disciplines, are not feasible at all. I don't see them in commercial testing labs.

I see there is an Add button on the global AR list too... not sure what the business reason is for that. None of the Client specific Sample points etc. will probably work. Don't have time to test, quicker to simply hide it in our installations.

It sounds like it is probably not worth it making the default specs work, but don't remove the default specs from the system please, it remains essential and we'll have to sort it out later

On the other hand it could be straighter forward, if clientless AR Create can be avoided - neither is absolutely necessary, except maybe the multi client Batches in research labs.

(note to self, log the smaller Spec bugs uncovered yesterday, e.g. dormant specs being listed for selection)

**Comment by lemoene** [comment]
from a design perspective, it should on the AR Create form boil down to:

If Client associated with the new AR

             completed Analysis Spec field with Client's default spec

If no Client associated

         display Specification selection widget


probably much easier said than done again

**Comment by lemoene** [comment]
correction, I see the function of AR Add on the global AR List - many labs won't be bothered with client specific sample points, licenses, earlier created batches or samples etc for the AR Create. Client Contacts really is the only compulsory one from among them?

**Comment by ramonski** [comment]
I really see no need for these calculation, because AR Add displays per default the local client Specs together with the lab specs:
<img width="1317" alt="happy hills senaite 2018-02-15 21-07-18" src="https://user-images.githubusercontent.com/713193/36278532-706a745c-1294-11e8-9b74-af823fcce966.png">

This functionality is just to select, e.g. one of these "Apple Pulp" specs per default if the option if the client has `Sample Type Specifications (Client)` set.

However, the whole calculation process slows down the AR Add process significantly for a really low benefit. IMO this option needs to go away in favor of performance and simplicity.

**Comment by lemoene** [comment]
In the simplest case, the requirement is just to get the Client's default An Spec onto the new ARs. Since users can still edit it on the AR, it ended up on the AR itself and not as a reference to the spec version at the time of AR Creation. Another thread, but that'll lose a lot of gunk it feels

So Analysis Spec can even go off the AR Create form, for as long as the Client's preferred spec at AR Create, gets applied in AR and WS views and eventual COAs. DBW sponsored this madness when we  were feature hungry... I don't think editing specs per AR is used at all now. They had many specs and dollars.

The screen shots captures the Spec before the Sample Type, it is normally done the other way round and the spec for that Sample Type applied.

Should we in this round simply remove the Spec from AR Create, and assign/reference in the bg creation process, the logic is

- User submits AR for Sample Type _Apple Pulp_

- LIMS looks up the Client's specification preference (or defaults to the system's) for _Apple Pulp_

- The specification and version reference is written to the new AR (or the values hard if that is more performance economical)

- Everytime the AR is displayed or printed, these Specs are applied

Bigger job now much neater, and we can get round with the users simply manually selecting the spec for now.

(The end goal got half implemented it seems, _Named Specs_, that like _Lab_ or _Client Specs_, are collections of specs for many Sample Types)

**Comment by lemoene** [comment]
Should the User decide to apply a different spec later, after the default was used to create the AR, they can modify it on the AR Edit tab

![image](https://user-images.githubusercontent.com/1196034/36282295-5d08374a-12a9-11e8-8fbf-87aaeec39569.png)

note nother small issue to log, the Specs offered for selection should only be for the applicable Sample Type. That is to ensure say Potable water specs get applied and not Sewage's

**Comment by lemoene** [comment]
example of 2 Specs for the same Sample Type

![image](https://user-images.githubusercontent.com/1196034/36282671-956e0848-12aa-11e8-9c00-bd23fe35aec1.png)

**Comment by lemoene** [comment]
Earlier comment edited for clarity, and **_Completely remove 'Editable Analysis Specifications'_**, #665 broken out as separate issue

**Comment by ramonski** [comment]
This option will be removed in future versions of SENAITE due to low benefit and high performance impact.

**Comment by lemoene** [comment]
Please don't remove the code completely. We'll need this back for environmental and cannabis labs (yesterday) probably as soon as March already. Will follow the above suggested auto add design
