### ISSUE TITLE
WS Assign Search parameters and Column Sorting don't sync

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.core#699]
## Steps to reproduce

Have lots of Analyses available in the system, _Received_, to create worksheets with.

Do so manually by selecting a Analysis Category and Client

![image](https://user-images.githubusercontent.com/1196034/36838392-b86d7f5c-1d47-11e8-897b-48e3859dfe0c.png)

## Current behavior

Say the user then want assign Analyses for Samples received on a specific date (to test with the others) and sorts on the header columns of the An returned by the filter. 

The system then seems to ignore the initially filtered set and loses correct Client and Ananlysis etc.

![image](https://user-images.githubusercontent.com/1196034/36838602-4b8b3112-1d48-11e8-82b5-4c656ef8ddea.png)

Pushing the more button of the first screen, loses only the Client.

![image](https://user-images.githubusercontent.com/1196034/36838909-218ede80-1d49-11e8-9ec0-37c2ba380255.png)

Cannot recreate it now, but also got https://github.com/senaite/senaite.core/issues/522 once

## Expected behavior

The column sort should maintain the Filter parameters set by the user

![image](https://user-images.githubusercontent.com/1196034/36839188-f5320f46-1d49-11e8-921c-1f4fb20be3ab.png)

**Comment by ramonski** [comment]
## Steps to reproduce

- Create 100 Analyses for Client A
- Create 100 Analyses for Client B
- Add a new worksheet and browse to the "Add Analyses" Tab
- Select Client A in the filter selection
- Click the "Show more" Button

## Current Behavior

Depending on the sort parameter, it might be that Analyses from Client B are displayed on the next chunk that get displayed after "show more" was clicked

## Expected Behavior

Only Analyses from Client A are displayed after "show more" was clicked
