### ISSUE TITLE
Always allow interim fields to be added to Analysis Services

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#751]
## Steps to reproduce

Create a new Analysis Service and switch to the "Methods" tab

## Current behavior

Interim fields are not visible until a Calculation was assigned and thus, cannot be added by the user.

## Expected behavior

Interim fields are always visible

## Screenshot (optional)

<img width="2910" alt="image 2018-03-28 17-21-06" src="https://user-images.githubusercontent.com/713193/38038970-77002f68-32ac-11e8-9178-285a57905956.png">

<img width="2908" alt="image 2018-03-28 17-19-54" src="https://user-images.githubusercontent.com/713193/38038907-623228ac-32ac-11e8-8eb0-b1059d8e3905.png">

**Comment by ramonski** [comment]
Why do we need this?

Sometimes it is needed to capture multiple results for one Analysis, e.g. 5 different areas in the sample like middle , right , left etc. and Interim fields are currently the only possibility to do so...

**Comment by xispa** [comment]
@ramonski related: https://github.com/senaite/senaite.core/issues/749
As we discussed earlier, we need to always keep interims that have been set manually. This approach covers the use case you explain here. But at the same time, calculation interims must be added too (if not yet present) on "Calculation" change. Otherwise, auto-calculations in results entry views will not work.

**Comment by xispa** [comment]
To avoid confusions, I suggest to rename the field label from "Calculation Interim Fields" to "Interim Fields" and remove the field description as well. The same machinery will work for both calculations and for multiple results with no further changes.
