### ISSUE TITLE
Remove "Composite" Field from AR/Sample

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#797]
## Description

This field is almost never needed and has as far as I can see no functionality except that it is there.

## Todo

Remove "Composite" Field

## Screenshot (optional)

<img width="1450" alt="analysis requests senaite 2018-04-25 22-43-23" src="https://user-images.githubusercontent.com/713193/39271715-1710f6de-48da-11e8-980c-6075596743f7.png">

**Comment by xispa** [comment]
"Composite" means the Sample is made of a composition of multiple samples. Eg. when analyzing water from a lake, the sampler may collect some samples from different places (1m and 2m deep, next to the south-coast, next to the lake input, etc.) and mix all them in the same bottle, so the results of the analyses performed later would "represent" the whole lake. Thus, this is only an informative field.

**Comment by ramonski** [comment]
Ok, does that mean we keep it or should we rather consider to do a `senaite.water` Add-on, where we extend these fields?
At least we have already a "SENAITE Water" logo: https://github.com/senaite/senaite.ci/blob/master/senaite_logo_manual.pdf

**Comment by xispa** [comment]
This is not water lab-specific. It also can be used for soil analyses, mining, food quality assessment, etc. I think the problem with this field is that only tells you if is composed or not, but when is ticked, the system does not explicitly force you to 1) choose multiple sample points (for single AR), 2) choose the samples is an aggregated of or 3) provide, at least, textual information. IMO, the lack of this additional info is the reason why this field is frequently ignored, even if the sample is, indeed, a composition.

When we add the functionality to allow the user to make derivative Samples  from other Samples (indefinitevely or not), we'll be able to discuss the feasibility of 1, and 2. Meanwhile, I suggest to keep this field as-is and if we believe is important at this point, maybe add 3.

**Comment by Espurna** [comment]
In my opinion this field doesn't belongs exclusively to water tests, this was an example. You may need composite samples for different liquid and solid samples: the combination of individual samples tries to minimize the effects of variability of the individual sample because of variations in the concentration of the elements. Not a lab analyst, but I thing this might happen for wine, different types water, different types of food, probably oils, soil, etc.

Now, it is true that this field has no functionality... May be we can find a better way to deal with this type of information "Dry matter", "composite", etc... A "tags" field?

**Comment by Espurna** [comment]
I just saw your comment @xispa

**Comment by ramonski** [comment]
Thanks @xispa, @Espurna. We'll leave it if it makes kind-of sense.

However, this is at the moment just a on/off switch, missing the information you described, e.g. "Samples taken from 1m/2m/3m ...".
IMO we could simply make the "Remarks" field available in the AR Add form to let the user exactly describe the sample in text.

What do you mean?

**Comment by xispa** [comment]
I think that what @Espurna suggests about allowing the user to add custom labels (or tags) to ARs (or even any "live" object such as Batches or Worksheets) would be very useful, specially for these kind of "informative" fields that may be lab-specific (thinking about "Adhoc" too). As long as the labels would be defined by the lab itself, these would not be meaningless. Re your suggestion @ramonski , I think is nice to add the "Remarks" field in the AR Add, maybe there is some information the requester want to provide for which there is no specific-field.

**Comment by ramonski** [comment]
Ok, I'm closing this one for now and let's keep the idea with the labels in mind. Also I'll open a new issue to make the "Remarks" field editable in AR Add.

By the way, the AR Add form is also capable to handle multiple Attachments ootb, so that already there the Attachments can be added by the user. Maybe also nice to have per default in AR Add...

**Comment by lemoene** [comment]
Apologies for coming in late again - we had ZA important Freedom day celebrations viva Mandela, long live - now moving on to Workers day.

Did not read the above in detail,  might have to come back, from a mile up:

Composite sampling, alt 'grab' sample, exists exactly because they are not Partitions. Partitions can be analysed separately. Composite sampling I often see as surface sampling of a dam, mining pit, field. They are always treated as one sample. https://www.bikalims.org/glossary/bika-open-source-lims-glossary#composite

The info could maybe also be stored on the Sample Point - but it helps to have it on AR Create form, views etc.

Sample reception remains the workflow step where most errors occur.

**Comment by lemoene** [comment]
The dam, pit or field is seen as one Sample point
