### ISSUE TITLE
Cannot retract single analysis service

### ISSUE THREAD

**Issue by grulisco** [senaite/senaite.core#821]
## Steps to reproduce
- Create AR with several analysis services
- submit results in AR view
- retract single result (because of e.g. mistake)

## Current behavior
All other results get retracted too and have to be submitted again.

## Expected behavior
Only result of selected service gets retracted.

## Screenshot (optional)
Retract Moisture:
![grafik](https://user-images.githubusercontent.com/25460329/39918960-71335ca8-5512-11e8-99ee-121f0b1fd611.png)

Calcium is retracted too:
![grafik](https://user-images.githubusercontent.com/25460329/39919044-b7efa6b0-5512-11e8-9c59-59f2b387d776.png)

**Comment by grulisco** [comment]
Same behaviour in Worksheet views: All services of the AR are retracted instead of the selected one only.

**Comment by xispa** [comment]
The function [`workflow.analysis.after_retract`](https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/workflow/analysis/events.py#L36) is automatically fired once the 'retract' workflow action for a given analysis is performed. One of the objectives of this function is to create a fresh copy of the retracted analysis here:

https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/workflow/analysis/events.py#L70-L72

This is the expected behavior, cause it allows the lab to introduce a new result while keeping the results entry history (for the same test). 

When an a new Analysis object is created, the subscriber [`ObjectInitializedEventHandler`](https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/subscribers/analysis.py#L24) is called automatically. The aim of this function is to transition the newly created analysis to a suitable state that fits well with the current state of the AR (e.g. if the AR is in `sample_received` state, the newly created analysis must be in this same state too). When a newly created Analysis is added to a `to_be_verified` Analysis Request, this function rolls-back the state of the Analysis Request to `sample_received`, which might seem correct at a first glance, cause this AR will contain now a new Analysis awaiting for new results. The problem is that for performing this roll-back, the function fires the transition `retract` for the whole AR, causing the retraction of all analyses it contains, as per `workflow.analysisrequest.events.after_retract`:

https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/subscribers/analysis.py#L39-L45

Thus, one might think that changing the workflow state of the AR to `sample_received` (by using [`changeWorkflowState`](https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/utils/__init__.py#L319) - that applies the new state without firing DCWorkflow transition -, instead of retracting the AR) would be enough in  [`ObjectInitializedEventHandler`](https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/subscribers/analysis.py#L44). Nevertheless, I feel this would be a hack and prone to future inconsistencies.

I think the following approach is a better solution, that will simplify the logic and will be less-prone to errors:

1. **The retraction of an Analysis Request should not cause the automatic retraction of the analyses it contains**, but only the AR itself. It would eventually mean the removal of `ObjectInitializedEventHandler` subscriber.

2. The automatic transition of newly created analyses to a suitable state that fits well with the current status of the AR should be responsibility of the places where the analysis is added, as we do in [`workflow.analysis.events.after_retract#L71`](https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/workflow/analysis/events.py#L71).

**Comment by xispa** [comment]
Umm, nope, the action "Retract" of an AR is precisely meant to retract all the analyses it contains. So in my proposed approach, the first suggestion "The retraction of an Analysis Request should not cause the automatic retraction of the analyses it contains" is wrong. 

Thus, I think the best option for now would simply be to just change the state of the AR to `sample_received` instead of firing `doActionFor(ar, 'retract')` here:

https://github.com/senaite/senaite.core/blob/cbef1aff9c07493430bbad1a8805ccda92426586/bika/lims/subscribers/analysis.py#L39-L45

.. and all this `ar.REQUEST['workflow_skiplist'].append("retract all analyses")` can be removed too
