### ISSUE TITLE
Localisation fails for left part of the webpage

### ISSUE THREAD

**Issue by Migulo** [senaite/senaite.core#870]
## Steps to reproduce
Change language from "English" to "German"
## Current behavior
The left part of the Senaite webpage does not change to German. For the other parts localisation works just fine.
## Expected behavior
The whole page should be localised correctly (I believe it worked with bika and/or senaite.lims 1.2.0).
## Screenshot (optional)
![image](https://user-images.githubusercontent.com/38714119/42077466-591488f8-7b79-11e8-91b6-5048ea017272.png)

**Comment by ramonski** [comment]
Hi @Migulo, thanks for reporting.

Could you please provide a screenshot, so that we know exactly which part of the screen you refer?

Thanks

**Comment by Migulo** [comment]
Hello ramonski,
 
Please find the screenshot above.

**Comment by ramonski** [comment]
Fixed with https://github.com/senaite/senaite.core/pull/846 and https://github.com/senaite/senaite.core/pull/883.

@Migulo: The fix will be available with the upcoming 1.2.7 release of `senaite.core`, so I'm closing this one for now. Please feel free to re-open it, when you still encounter this behavior after you upgraded to 1.2.7.

Thanks
